/**
 * Coach Alert Service
 *
 * CRUD operations for coach_alerts table.
 * Alerts are generated by application logic (edge function or service role)
 * and can be read/updated (mark read/dismissed) by the coach.
 */
import { supabase } from '@/integrations/supabase/client';
import type { CoachAlert, AlertSeverity, AlertType } from '@/types/checkin';

/**
 * Get alerts for a coach (trainer), newest first, with optional filters.
 */
export async function getCoachAlerts(
  trainerId: string,
  options?: {
    severity?: AlertSeverity;
    alertType?: AlertType;
    includeRead?: boolean;
    includeDismissed?: boolean;
    limit?: number;
  }
): Promise<{ alerts: CoachAlert[]; error: string | null }> {
  try {
    let query = supabase
      .from('coach_alerts')
      .select('*')
      .eq('trainer_id', trainerId)
      .order('created_at', { ascending: false });

    if (options?.severity) {
      query = query.eq('severity', options.severity);
    }

    if (options?.alertType) {
      query = query.eq('alert_type', options.alertType);
    }

    // Default: show unread, non-dismissed alerts
    if (options?.includeRead !== true) {
      query = query.eq('read', false);
    }
    if (options?.includeDismissed !== true) {
      query = query.eq('dismissed', false);
    }

    if (options?.limit) {
      query = query.limit(options.limit);
    }

    const { data, error } = await query;

    if (error) {
      return { alerts: [], error: error.message };
    }

    return { alerts: (data ?? []) as unknown as CoachAlert[], error: null };
  } catch (err: unknown) {
    return {
      alerts: [],
      error: err instanceof Error ? err.message : 'Failed to fetch coach alerts',
    };
  }
}

/**
 * Mark a single alert as read.
 */
export async function markAlertRead(
  alertId: string
): Promise<{ success: boolean; error: string | null }> {
  try {
    const { error } = await supabase
      .from('coach_alerts')
      .update({ read: true, read_at: new Date().toISOString() })
      .eq('id', alertId);

    if (error) {
      return { success: false, error: error.message };
    }

    return { success: true, error: null };
  } catch (err: unknown) {
    return {
      success: false,
      error: err instanceof Error ? err.message : 'Failed to mark alert read',
    };
  }
}

/**
 * Mark multiple alerts as read in a single batch.
 */
export async function markAlertsRead(
  alertIds: string[]
): Promise<{ success: boolean; error: string | null }> {
  try {
    if (alertIds.length === 0) return { success: true, error: null };

    const { error } = await supabase
      .from('coach_alerts')
      .update({ read: true, read_at: new Date().toISOString() })
      .in('id', alertIds);

    if (error) {
      return { success: false, error: error.message };
    }

    return { success: true, error: null };
  } catch (err: unknown) {
    return {
      success: false,
      error: err instanceof Error ? err.message : 'Failed to mark alerts read',
    };
  }
}

/**
 * Dismiss an alert (soft-delete: hidden from default views).
 */
export async function dismissAlert(
  alertId: string
): Promise<{ success: boolean; error: string | null }> {
  try {
    const { error } = await supabase
      .from('coach_alerts')
      .update({ dismissed: true })
      .eq('id', alertId);

    if (error) {
      return { success: false, error: error.message };
    }

    return { success: true, error: null };
  } catch (err: unknown) {
    return {
      success: false,
      error: err instanceof Error ? err.message : 'Failed to dismiss alert',
    };
  }
}

/**
 * Get unread alert count for a coach (badge indicator).
 */
export async function getUnreadAlertCount(
  trainerId: string
): Promise<{ count: number; error: string | null }> {
  try {
    const { count, error } = await supabase
      .from('coach_alerts')
      .select('*', { count: 'exact', head: true })
      .eq('trainer_id', trainerId)
      .eq('read', false)
      .eq('dismissed', false);

    if (error) {
      return { count: 0, error: error.message };
    }

    return { count: count ?? 0, error: null };
  } catch (err: unknown) {
    return {
      count: 0,
      error: err instanceof Error ? err.message : 'Failed to count unread alerts',
    };
  }
}

import type { Json } from '@/integrations/supabase/types';

export interface GenerateAlertInput {
  client_id: string;
  trainer_id: string;
  alert_type: AlertType;
  severity: AlertSeverity;
  title: string;
  message: string;
  metadata?: Json;
}

/**
 * Generate a single coach alert.
 * Intended for use by edge functions or service-role contexts.
 * On the client side, this is typically called via an edge function.
 */
export async function generateAlert(
  input: GenerateAlertInput
): Promise<{ alert: CoachAlert | null; error: string | null }> {
  try {
    const { data, error } = await supabase
      .from('coach_alerts')
      .insert({
        client_id: input.client_id,
        trainer_id: input.trainer_id,
        alert_type: input.alert_type,
        severity: input.severity,
        title: input.title,
        message: input.message,
       metadata: input.metadata ?? null,
        read: false,
        dismissed: false,
      })
      .select()
      .single();

    if (error) {
      return { alert: null, error: error.message };
    }

    return { alert: data as unknown as CoachAlert, error: null };
  } catch (err: unknown) {
    return {
      alert: null,
      error: err instanceof Error ? err.message : 'Failed to generate alert',
    };
  }
}
