import { TrainingPlan, WorkoutSession, WorkoutExercise, TrainingWeek, TrainingPlanInput } from '@/types';
import { GOAL_TRAINING_PARAMS, EXPERIENCE_ADJUSTMENTS } from './constants';
import { selectExercisesForSession } from './exerciseSelectors';
import { buildWorkoutPrescription } from './loadPrescription';
import { createSeededRng } from '@/utils/random';

const WEEK_OPTIONS = [4, 5, 6, 7, 8] as const;

/**
 * Temporary placeholder for the TrainingPlan id before it is persisted.
 * The authoritative identity is `training_plans.id` — a UUID generated by
 * PostgreSQL inside `save_training_plan`. This placeholder is replaced with
 * the real persisted UUID as soon as the plan is saved/reloaded, so it is
 * never used as the `session_logs.plan_id` FK (which is a UUID column).
 */
const createPlanPlaceholderId = (): string =>
  typeof crypto !== 'undefined' && 'randomUUID' in crypto
    ? crypto.randomUUID()
    : `plan-${Date.now()}-${Math.random().toString(16).slice(2)}`;

const trainingObjective = (goal: TrainingPlanInput['primaryGoal']): TrainingPlan['objective'] => {
  switch (goal) {
    case 'fat_loss': return 'Lose body fat while preserving strength.';
    case 'muscle_gain': return 'Build lean muscle with structured volume and progression.';
    case 'recomposition': return 'Improve body composition through strength and metabolic training.';
    case 'maintenance': return 'Maintain strength and build consistency without excess fatigue.';
    default: return 'Build consistency and strength safely.';
  }
};

const phasePlan = (goal: TrainingPlanInput['primaryGoal'], duration: number) => {
  const breakPoint = Math.ceil(duration / 2);
  return [
    {
      key: 'foundation',
      name: 'Foundation',
      objective: goal === 'fat_loss'
        ? 'Build movement quality, prepare tendons, and raise baseline calorie burn.'
        : 'Build strength, technique, and consistent training habits.',
      startWeek: 1,
      endWeek: breakPoint,
    },
    {
      key: 'build',
      name: 'Build',
      objective: goal === 'fat_loss'
        ? 'Increase training demand with controlled volume and short rests.'
        : 'Progress strength and muscle through targeted overload.',
      startWeek: breakPoint + 1,
      endWeek: duration,
    },
  ];
};

const chooseDuration = (frequency: number): number => {
  if (frequency <= 3) return 4;
  if (frequency === 4) return 6;
  if (frequency === 5) return 7;
  return 8;
};

const sessionPatternForFrequency = (daysPerWeek: number) => {
  if (daysPerWeek <= 3) return Array(daysPerWeek).fill('full_body');
  if (daysPerWeek === 4) return ['upper', 'lower', 'upper', 'lower'];
  if (daysPerWeek === 5) return ['upper', 'lower', 'upper', 'lower', 'full_body'];
  if (daysPerWeek === 6) return ['push', 'pull', 'legs', 'push', 'pull', 'legs'];
  return ['full_body', 'upper', 'lower', 'push', 'pull', 'legs'].slice(0, daysPerWeek);
};

const phaseTypeForGoal = (goal: TrainingPlanInput['primaryGoal']): TrainingPlan['phase'] => {
  switch (goal) {
    case 'fat_loss': return 'endurance';
    case 'muscle_gain': return 'hypertrophy';
    case 'recomposition': return 'hypertrophy';
    case 'maintenance': return 'strength';
    default: return 'strength';
  }
};

const mapSessionLabel = (sessionType: WorkoutSession['sessionType']) => {
  switch (sessionType) {
    case 'upper': return 'Upper Body';
    case 'lower': return 'Lower Body';
    case 'push': return 'Push Day';
    case 'pull': return 'Pull Day';
    case 'legs': return 'Leg Day';
    case 'full_body': return 'Full Body';
    case 'cardio': return 'Conditioning';
    case 'rest': return 'Recovery';
    default: return 'Workout';
  }
};

const buildWeek = (
  weekNumber: number,
  sessionPattern: readonly ('upper' | 'lower' | 'push' | 'pull' | 'legs' | 'full_body')[],
  client: TrainingPlanInput,
  phaseName: string,
  phaseObjective: string,
): TrainingWeek => {
  const sessions: WorkoutSession[] = sessionPattern.map((sessionType, idx) => {
    const dayNumber = idx + 1;
    const exercises = selectExercisesForSession(
      sessionType,
      client.trainingExperience,
      client.equipmentAvailable ?? client.equipment,
      createSeededRng(`${client.id}-${weekNumber}-${sessionType}`),
    );

        // Week 1 / Day 1 is the coach-established baseline: each loaded exercise
    // gets its OWN equipment-aware default load here (quantized in
    // loadPrescription). A single global load is NEVER applied — the coach
    // finalizes each exercise's first-session load via the Training page's
    // per-exercise editor before the plan is persisted. Later weeks use the
    // same per-exercise defaults; the runtime progression engine
    // (progressSelector) adapts them from session_logs.

    const workoutExercises: WorkoutExercise[] = exercises.map(exercise => {
      const goalParams = GOAL_TRAINING_PARAMS[client.primaryGoal] || GOAL_TRAINING_PARAMS.maintenance;
      const prescription = buildWorkoutPrescription(
        exercise,
        client.preferredTrainingStyle,
        client.trainingExperience,
        client.equipmentAvailable ?? client.equipment,
        goalParams.reps,
        goalParams.intensity,
      );

      const isCompound = ['squat', 'deadlift', 'bench', 'row', 'press', 'pull-up', 'dip'].some(token => exercise.name.toLowerCase().includes(token));
      const sets = Math.max(3, goalParams.sets + (isCompound ? 1 : 0));
      const rest = isCompound ? Math.max(90, goalParams.rest) : goalParams.rest;

      return {
        exercise,
        sets,
        reps: goalParams.reps,
        rest,
        intensity: prescription.targetRPE,
        tempo: client.trainingExperience === 'beginner' ? '3-1-2-0' : '2-0-2-0',
        notes: client.trainingExperience === 'beginner'
          ? 'Focus on clean setup, controlled descent, and stable position.'
          : 'Move with control and use the full rep range. Log RPE for each set.',
        targetRPE: prescription.targetRPE,
        targetLoad: prescription.targetLoad,
        loadUnit: prescription.loadUnit,
        equipmentType: exercise.equipment.length === 0 ? 'bodyweight' : 'barbell',
        progressionHint: prescription.progressionHint,
        progressionRule: 'Use RPE and rep completion to guide the next session load.',
      };
    });

    const weekGoal = GOAL_TRAINING_PARAMS[client.primaryGoal] || GOAL_TRAINING_PARAMS.maintenance;
    return {
      id: `${client.id}-w${weekNumber}-s${dayNumber}`,
      weekNumber,
      dayNumber,
      sessionType,
      name: `${mapSessionLabel(sessionType)} • Week ${weekNumber}`,
      duration: client.sessionDuration,
      exercises: workoutExercises,
      notes: `Complete this workout with a strong warm-up. Track RPE for each set and keep the final set within ${weekGoal.reps} at ${weekGoal.intensity}.`,
    };
  });

  return {
    weekNumber,
    phase: phaseName,
    objective: phaseObjective,
    sessions,
  };
};

export function generateDynamicTrainingPlan(client: TrainingPlanInput): TrainingPlan {
  const daysPerWeek = Math.min(Math.max(client.trainingDaysPerWeek, 3), 6);
  const duration = chooseDuration(daysPerWeek);
  const split = daysPerWeek <= 3 ? 'full_body' : daysPerWeek === 4 ? 'upper_lower' : 'push_pull_legs';
  const phase = phaseTypeForGoal(client.primaryGoal);
  const phases = phasePlan(client.primaryGoal, duration);
  const sessionPattern = sessionPatternForFrequency(daysPerWeek);

  const weeks: TrainingWeek[] = Array.from({ length: duration }, (_, index) => {
    const weekNumber = index + 1;
    const currentPhase = phases.find(p => weekNumber >= p.startWeek && weekNumber <= p.endWeek) ?? phases[phases.length - 1];
    return buildWeek(weekNumber, sessionPattern, client, currentPhase.name, currentPhase.objective);
  });

  const workouts = weeks.flatMap(week => week.sessions);

  return {
    id: createPlanPlaceholderId(),
    clientId: client.id,
    name: `${client.primaryGoal.replace('_', ' ')} ${split.replace('_', '/')} Program`,
    objective: trainingObjective(client.primaryGoal),
    duration,
    frequency: daysPerWeek,
    split,
    phase,
    phases,
    weeks,
    workouts,
    progressionScheme: 'Autoregulated progression using double progression and RPE-based load decisions.',
    programDescription: `A ${duration}-week training block designed for ${client.primaryGoal.replace('_', ' ')} with ${daysPerWeek}-day frequency and equipment-aware loading.`,
        // Coach-owned scheduling anchor for Week 1 / Day 1 (calendar-gated progression).
    startDate: new Date().toISOString().slice(0, 10),
    createdAt: new Date().toISOString(),
  };
}

/**
 * Apply the coach's per-exercise first-session loads (Week 1 / Day 1) into the
 * generated plan, immutably. Each loaded exercise keeps its OWN targetLoad; the
 * coach's value replaces the generated default and is snapped to that
 * equipment's increment (2.5 kg for barbell/dumbbell/cable, 5 kg for machines).
 * Bodyweight exercises are left untouched (they remain bodyweight / targetLoad 0).
 *
 * Only the first session (weeks[0].sessions[0]) is editable - that is the
 * coach-established baseline. Later sessions and weeks are unchanged and are
 * adapted at runtime by progressSelector from session_logs. This never mutates
 * the plan the client later logs into; it only shapes the prescription at
 * generation/save time.
 */

// Coarsest load increment per equipment type stored on a WorkoutExercise.
const EQUIPMENT_INCREMENT: Record<string, number> = {
  barbell: 2.5,
  dumbbell: 2.5,
  cable: 2.5,
  machine: 5,
  bodyweight: 1,
};
const equipmentIncrement = (ex: WorkoutExercise): number =>
  ex.loadUnit === 'bodyweight' ? 1 : (EQUIPMENT_INCREMENT[ex.equipmentType ?? ''] ?? 2.5);
const quantizeToIncrement = (load: number, increment: number): number => {
  if (increment <= 0) return Math.round(load);
  const q = Math.round(load / increment) * increment;
  return Math.max(increment, Math.round(q * 100) / 100);
};

export function applyFirstSessionLoads(
  plan: TrainingPlan,
  loadsByExerciseId: Record<string, number>,
): TrainingPlan {
  if (!plan.weeks.length) return plan;
  const updatedWeeks = plan.weeks.map((week, weekIndex) => {
    if (weekIndex !== 0) return week;
    return {
      ...week,
      sessions: week.sessions.map((session, sessionIndex) => {
        if (sessionIndex !== 0) return session;
        return {
          ...session,
          exercises: session.exercises.map((ex): WorkoutExercise => {
            // Bodyweight exercises never receive a load - they stay bodyweight/0.
            if (ex.loadUnit === 'bodyweight') return ex;
            const next = loadsByExerciseId[ex.exercise.id];
            if (typeof next !== 'number' || Number.isNaN(next) || next < 0) return ex;
            return { ...ex, targetLoad: quantizeToIncrement(next, equipmentIncrement(ex)) };
          }),
        };
      }),
    };
  });
  return { ...plan, weeks: updatedWeeks };
}
